# Generated by Django 2.2.7 on 2019-11-06 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20191106_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profile name'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profile name'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='title',
            field=models.CharField(choices=[('Dr', 'Doctor'), ('LPN', 'Licensed practical nurse'), ('RN', 'Registered nurse'), ('APRN', ' Advanced practice registered nurse')], max_length=5, verbose_name='title (role)'),
        ),
    ]
