# Generated by Django 2.2.7 on 2019-11-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20191106_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='title',
            field=models.CharField(choices=[('Dr', 'Doctor (Dr)'), ('LPN', 'Licensed practical nurse (LPN)'), ('RN', 'Registered nurse (RN)'), ('APRN', ' Advanced practice registered nurse (APRN)')], max_length=5, verbose_name='title (role)'),
        ),
    ]
