# Generated by Django 2.2.7 on 2019-11-12 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20191110_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to=settings.AUTH_USER_MODEL, verbose_name='profile name'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_user', to=settings.AUTH_USER_MODEL, verbose_name='profile name'),
        ),
    ]
