# Generated by Django 2.2.7 on 2019-11-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20191106_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='height (m/cm)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='weight (kg)')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='BloodRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('blood_genotype', models.CharField(max_length=2)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Patient')),
            ],
        ),
    ]
