# Generated by Django 2.2.7 on 2019-11-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20191110_1956'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrecord',
            name='blood_genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AO', 'AO'), ('AB', 'AB'), ('BO', 'BO'), ('BB', 'BB'), ('OO', 'OO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='bloodrecord',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O(+) Positive'), ('O-', 'O(-) Negative'), ('A+', 'A(+) Positive'), ('A-', 'O(-) Negative'), ('AB+', 'AB(+) Positive'), ('AB-', 'AB(-) Negative')], max_length=3),
        ),
        migrations.CreateModel(
            name='LocationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='Abuja', max_length=255)),
                ('town', models.CharField(choices=[('Abaji', 'Abaji'), ('Garki', 'Garki'), ('Bwari', 'Bwari'), ('Kuje', 'Kuje'), ('Dutse', 'Dutse'), ('Gwagwalada', 'Gwagwalada')], max_length=255)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(choices=[('Ebola', 'Ebola'), ('Malaria', 'Malaria'), ('Typhoid', 'Typhoid'), ('Hepatitis', 'Hepatitis'), ('Tuberculosis', 'Tuberculosis'), ('Others', 'Others')], max_length=255)),
                ('description', models.TextField()),
                ('test_result', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Patient')),
            ],
        ),
    ]
